config/routes.rb
Rails.application.routes.draw do
  get 'device_count', to: 'device_count#index', defaults: { format: 'json' }
  get 'total_payout', to: 'total_payout#index', defaults: { format: 'json' }

  get 'offer_target_players/index/:offer_target_id', to: 'offer_target_players#index', as: :offer_target_players

  resources :offer_targets
  resources :offers
  resources :players
  resources :devices
  resources :genders
  resources :locales
  resources :operating_systems

  root "players#index"
end

app/models/offer_target.rb
require 'utils'

class OfferTarget < ApplicationRecord
  include Utils

  belongs_to :offer
  belongs_to :operating_system
  belongs_to :locale
  belongs_to :gender

  def OfferTarget.total_payout(min_age=1, max_age=150)
    query_total_payout_in_cents = <<-SQL
      SELECT COALESCE(SUM(o.payout_cents), 0) AS total_payout_in_cents
      FROM offers o
      INNER JOIN (
        SELECT offer_id, player_id
        FROM offer_targets ot
        INNER JOIN players p ON
          p.gender_id = ot.gender_id AND
          p.birthdate BETWEEN
            CURRENT_DATE - INTERVAL '1 year' * ot.max_player_age AND
            CURRENT_DATE - INTERVAL '1 year' * ot.min_player_age
        INNER JOIN devices d ON
          d.player_id = p.id AND
          d.operating_system_id = ot.operating_system_id AND
          d.locale_id = ot.locale_id AND
          (d.os_major_version > ot.min_os_major_version
          OR
          (d.os_major_version = ot.min_os_major_version AND
            d.os_minor_version > ot.min_os_minor_version)
          OR
          (d.os_major_version = ot.min_os_major_version AND
            d.os_minor_version = ot.min_os_minor_version AND
            d.os_patch_version >= ot.min_os_patch_version))
        WHERE p.birthdate BETWEEN
          CURRENT_DATE - INTERVAL '1 year' * #{max_age} AND
          CURRENT_DATE - INTERVAL '1 year' * #{min_age}
      ) matching_offers ON matching_offers.offer_id = o.id
SQL

    result = ActiveRecord::Base.connection.exec_query(query_total_payout_in_cents)
    key,value = result.first.first
    value
  end

end

app/controllers/offer_targets_controller.rb
require 'utils'
class OfferTargetsController < ApplicationController
  include Utils
  before_action :set_offer_target, only: %i[ show edit update destroy ]

  # GET /offer_targets or /offer_targets.json
  def index
    @offer_targets = OfferTarget.all
    @min_version = '0.0.2'
    @max_version = '10.0'
    @ios_count = Device.with_os('ios').gr_eq_to_vers(parse_vers(@min_version)).ls_eq_to_vers(parse_vers(@max_version)).count
    @android_count = Device.with_os('android').gr_eq_to_vers(parse_vers(@min_version)).ls_eq_to_vers(parse_vers(@max_version)).count
  end

  # GET /offer_targets/1 or /offer_targets/1.json
  def show
  end

  # GET /offer_targets/new
  def new
    @offer_target = OfferTarget.new
  end

  # GET /offer_targets/1/edit
  def edit
  end

  # POST /offer_targets or /offer_targets.json
  def create
    @offer_target = OfferTarget.new(offer_target_params)

    respond_to do |format|
      if @offer_target.save
        format.html { redirect_to offer_target_url(@offer_target), notice: "Offer target was successfully created." }
        format.json { render :show, status: :created, location: @offer_target }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @offer_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offer_targets/1 or /offer_targets/1.json
  def update
    respond_to do |format|
      if @offer_target.update(offer_target_params)
        format.html { redirect_to offer_target_url(@offer_target), notice: "Offer target was successfully updated." }
        format.json { render :show, status: :ok, location: @offer_target }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @offer_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offer_targets/1 or /offer_targets/1.json
  def destroy
    @offer_target.destroy

    respond_to do |format|
      format.html { redirect_to offer_targets_url, notice: "Offer target was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer_target
      @offer_target = OfferTarget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def offer_target_params
      params.require(:offer_target).permit(:offer_id, :min_player_age, :max_player_age, :operating_system_id, :min_os_major_version, :min_os_minor_version, :min_os_patch_version, :locale_id, :gender_id)
    end
end

app/helpers/offer_targets_helper.rb
module OfferTargetsHelper
end

app/views/offer_targets/_form.html.erb
<%= form_with(model: offer_target) do |form| %>
  <% if offer_target.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(offer_target.errors.count, "error") %> prohibited this offer_target from being saved:</h2>

      <ul>
        <% offer_target.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :offer_id, style: "display: block" %>
    <%= form.collection_select(:offer_id,
                              Offer.all,
                              :id,
                              :title,
                              { :prompt => 'Select',
                                :selected => offer_target.operating_system_id
                              }, { class: 'form-control' }) %>
  </div>

  <div>
    <%= form.label :min_player_age, style: "display: block" %>
    <%= form.number_field :min_player_age %>
  </div>

  <div>
    <%= form.label :max_player_age, style: "display: block" %>
    <%= form.number_field :max_player_age %>
  </div>

  <div>
    <%= form.label :operating_system_id, style: "display: block" %>
    <%= form.collection_select(:operating_system_id,
                              OperatingSystem.all,
                              :id,
                              :name,
                              { :prompt => 'Select',
                                :selected => offer_target.operating_system_id
                              }, { class: 'form-control' }) %>
  </div>

  <div>
    <%= form.label :min_os_major_version, style: "display: block" %>
    <%= form.number_field :min_os_major_version %>
  </div>

  <div>
    <%= form.label :min_os_minor_version, style: "display: block" %>
    <%= form.number_field :min_os_minor_version %>
  </div>

  <div>
    <%= form.label :min_os_patch_version, style: "display: block" %>
    <%= form.number_field :min_os_patch_version %>
  </div>

  <div>
    <%= form.label :locale_id, style: "display: block" %>
    <%= form.collection_select(:locale_id,
                              Locale.all,
                              :id,
                              :code,
                              { :prompt => 'Select',
                                :selected => offer_target.locale_id
                              }, { class: 'form-control' }) %>
  </div>

  <div>
    <%= form.label :gender_id, style: "display: block" %>
    <%= form.collection_select(:gender_id,
                              Gender.all,
                              :id,
                              :name,
                              { :prompt => 'Select',
                                :selected => offer_target.gender_id
                              }, { class: 'form-control' }) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/offer_targets/_offer_target.html.erb
<div id="<%= dom_id offer_target %>">
  <p>
    <strong>Offer:</strong>
    <%= offer_target.offer.title %>
  </p>

  <p>
    <strong>Player age:</strong>
    <%= offer_target.min_player_age %> - <%= offer_target.max_player_age %>
  </p>

  <p>
    <strong>Operating system:</strong>
    <%= offer_target.operating_system.name if offer_target.operating_system %>
  </p>

  <p>
    <strong>Minimum OS version:</strong>
    <%= offer_target.min_os_major_version %>.<%= offer_target.min_os_minor_version %>.<%= offer_target.min_os_patch_version %>
  </p>

  <p>
    <strong>Locale:</strong>
    <%= offer_target.locale.code %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= offer_target.gender.name %>
  </p>

</div>

app/views/offer_targets/_offer_target_table_row.html.erb
<tr id="<%= dom_id item %>">
  <td>
    <%= item.offer.title %>
  </td>

  <td>
    <%= item.min_player_age %> - <%= item.max_player_age %>
  </td>

  <td>
    <%= item.operating_system.name if item.operating_system %>
  </td>

  <td>
    <%= item.min_os_major_version %>.<%= item.min_os_minor_version %>.<%= item.min_os_patch_version %>
  </td>

  <td>
    <%= item.locale.code %>
  </td>

  <td>
    <%= item.gender.name %>
  </td>

  <td>
    <%= link_to "Show", item %>
  </td>

  <td>
    <%= link_to "Matching users", offer_target_players_path(item) %>
  </td>

</tr>

app/views/offer_targets/edit.html.erb
<h1>Editing offer target</h1>

<%= render "form", offer_target: @offer_target %>

<br>

<div>
  <%= link_to "Show this offer target", @offer_target %> |
  <%= link_to "Back to offer targets", offer_targets_path %>
</div>

app/views/offer_targets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Offer targets</h1>

<p>
<!--   Total payout (ages 15-25): <strong> <%= OfferTarget.total_payout(15, 25) %></strong> -->
<!-- <br/> -->
<!--   Total payout (ages 30-40): <strong> <%= OfferTarget.total_payout(30, 40) %></strong> -->
<!-- <br/> -->
  Total payout (ages 14-100): <strong> <%= OfferTarget.total_payout(14, 100) %></strong>
</p>

<p>
<!--
  IOS device count between version range: <%= @min_version %> - <%= @max_version %>: <strong> <%= @ios_count %> </strong>
<br/>
-->
  Android device count between version range: <%= @min_version %> - <%= @max_version %>: <strong> <%= @android_count %> </strong>
</p>

<%= link_to "New offer target", new_offer_target_path %>

<div id="offer_targets">
  <table>
    <tr>
      <th>Offer</th>
      <th>Player age</th>
      <th>Operating system</th>
      <th>Minimum OS version</th>
      <th>Locale</th>
      <th>Gender</th>
      <th></th>
      <th></th>
    </tr>

    <% @offer_targets.each do |offer_target| %>
      <%= render "offer_target_table_row", item: offer_target %>
    <% end %>
  </table>
</div>

app/views/offer_targets/new.html.erb
<h1>New offer target</h1>

<%= render "form", offer_target: @offer_target %>

<br>

<div>
  <%= link_to "Back to offer targets", offer_targets_path %>
</div>

app/views/offer_targets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @offer_target %>

<div>
  <%= link_to "Edit this offer target", edit_offer_target_path(@offer_target) %> |
  <%= link_to "Back to offer targets", offer_targets_path %>

  <%= button_to "Destroy this offer target", @offer_target, method: :delete, prompt: true %>

  <%= link_to "Show matching users", offer_target_players_path(@offer_target) %>

</div>