config/routes.rb
Rails.application.routes.draw do
  get 'device_count', to: 'device_count#index', defaults: { format: 'json' }
  get 'total_payout', to: 'total_payout#index', defaults: { format: 'json' }

  get 'offer_target_players/index/:offer_target_id', to: 'offer_target_players#index', as: :offer_target_players

  resources :offer_targets
  resources :offers
  resources :players
  resources :devices
  resources :genders
  resources :locales
  resources :operating_systems

  root "players#index"
end

app/models/offer.rb
class Offer < ApplicationRecord
  monetize :payout_cents

  validates :title,
    presence: true

  validates :points,
    presence: true,
    numericality: { :greater_than_or_equal_to => 0 }

  validates :payout,
    presence: true,
    numericality: { :greater_than_or_equal_to => 0 }

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: %i[ show edit update destroy ]

  # GET /offers or /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1 or /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers or /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to offer_url(@offer), notice: "Offer was successfully created." }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1 or /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to offer_url(@offer), notice: "Offer was successfully updated." }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1 or /offers/1.json
  def destroy
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url, notice: "Offer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def offer_params
      params.require(:offer).permit(:title, :header, :description, :points, :payout, :payout_cents)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_with(model: offer) do |form| %>
  <% if offer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
        <% offer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :header, style: "display: block" %>
    <%= form.text_field :header %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :points, style: "display: block" %>
    <%= form.number_field :points %>
  </div>

  <div>
    <%= form.label :payout, style: "display: block" %>
    <%= form.number_field :payout, step: :any %>

  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/offers/_offer.html.erb
<div id="<%= dom_id offer %>">
  <p>
    <strong>
      <%= offer.title %> - <%= offer.header %>
    </strong>
  </p>

  <p>
    <%= offer.description %>
  </p>

  <p>
    <strong>Points:</strong>
    <%= offer.points %>
    |
    <strong>Payout:</strong>
    <%= humanized_money_with_symbol offer.payout %>
  </p>

</div>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render "form", offer: @offer %>

<br>

<div>
  <%= link_to "Show this offer", @offer %> |
  <%= link_to "Back to offers", offers_path %>
</div>

app/views/offers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Offers</h1>

<%= link_to "New offer", new_offer_path %>

<div id="offers">
  <% @offers.each do |offer| %>
    <%= render offer %>
    <p>
      <%= link_to "Show this offer", offer %>
    </p>
  <% end %>
</div>

app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render "form", offer: @offer %>

<br>

<div>
  <%= link_to "Back to offers", offers_path %>
</div>

app/views/offers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @offer %>

<div>
  <%= link_to "Edit this offer", edit_offer_path(@offer) %> |
  <%= link_to "Back to offers", offers_path %>

  <%= button_to "Destroy this offer", @offer, method: :delete %>
</div>