config/routes.rb
Rails.application.routes.draw do
  get 'device_count', to: 'device_count#index', defaults: { format: 'json' }
  get 'total_payout', to: 'total_payout#index', defaults: { format: 'json' }

  get 'offer_target_players/index/:offer_target_id', to: 'offer_target_players#index', as: :offer_target_players

  resources :offer_targets
  resources :offers
  resources :players
  resources :devices
  resources :genders
  resources :locales
  resources :operating_systems

  root "players#index"
end

app/views/layouts/_header.html.erb
<!-- <header class="navbar navbar-fixed-top navbar-inverse"> -->
<!--   <div class='container'> -->
<header>
  <div>
    <nav>
      <ul>
        <li> <%= link_to "Reports", root_url %> </li>
        <li> <%= link_to "Offer Targets", offer_targets_url %> </li>
        <li> <%= link_to "Offers", offers_url %> </li>
        <li> <%= link_to "Players and Devices", players_url %> </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChallengeProject</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- defer: true ensures that we don't run before dom is rendered ('cause we need the <div id='root'>...) -->
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%#= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <%= yield %>
    </div>

    <%#= debug(params) if Rails.env.development? %>
  </body>
</html>